discourse_turnstile:
  discourse_turnstile_enabled:
    default: false
    client: true
  turnstile_site_key:
    default: ''
    client: true
  turnstile_secret_key:
    default: ''
    client: false
